package com.anaptecs.jeaf.validation.api.spring;

import com.anaptecs.jeaf.validation.api.ValidationExecutorReactive;
import org.springframework.stereotype.Component;

/**
 * Class is intended to be used that in case of Spring Boot {@link ValidationExecutorReactive} does not have to be
 * injected into every POJO when using validation in POJO builders that e.g. are generated by JEAF Generator.
 *
 * @author JEAF Development Team
 */
@Component
public class SpringValidationExecutorReactive {
  /**
   * Reference to {@link ValidationExecutorReactive} as it was configured for this environment.
   */
  private static ValidationExecutorReactive reactiveValidationExecutor;

  /**
   * Method returns {@link ValidationExecutorReactive} that is configured for the current environment.
   *
   * @return {@link ValidationExecutorReactive} Available {@link ValidationExecutorReactive} for the current
   * environment. The method never returns null.
   */
  public static ValidationExecutorReactive getReactiveValidationExecutor( ) {
    ValidationExecutorReactive lReactiveValidationExecutor;
    if (reactiveValidationExecutor != null) {
      lReactiveValidationExecutor = reactiveValidationExecutor;
    }
    else {
      lReactiveValidationExecutor = new ValidationExecutorReactive() {
      };
    }
    return lReactiveValidationExecutor;
  }

  /**
   * Operation is intended to be used by Spring during bootstrapping to set configured
   * {@link ValidationExecutorReactive}.
   *
   * @param pReactiveValidationExecutor Validation executor that is configured for this environment.
   */
  public SpringValidationExecutorReactive( ValidationExecutorReactive pReactiveValidationExecutor ) {
    reactiveValidationExecutor = pReactiveValidationExecutor;
  }
}
