package com.anaptecs.jeaf.validation.api.spring;

import com.anaptecs.jeaf.validation.api.ValidationExecutor;
import org.springframework.stereotype.Component;

/**
 * Class is intended to be used that in case of Spring Boot {@link ValidationExecutor} does not have to be injected into
 * every POJO when using validation in POJO builders that e.g. are generated by JEAF Generator.
 *
 * @author JEAF Development Team
 */
@Component
public class SpringValidationExecutor {
  /**
   * Reference to ValidationExecutor as it was configured for this environment.
   */
  private static ValidationExecutor validationExecutor;

  /**
   * Method returns {@link ValidationExecutor} that is configured for the current environment.
   *
   * @return {@link ValidationExecutor} Available {@link ValidationExecutor} for the current environment. The method
   * never returns null.
   */
  public static ValidationExecutor getValidationExecutor( ) {
    ValidationExecutor lValidationExecutor;
    if (validationExecutor != null) {
      lValidationExecutor = validationExecutor;
    }
    else {
      lValidationExecutor = new ValidationExecutor() {
      };
    }
    return lValidationExecutor;
  }

  /**
   * Operation is intended to be used by Spring during bootstrapping to set configured {@link ValidationExecutor}.
   *
   * @param pReactiveValidationExecutor Validation executor that is configured for this environment.
   */
  public SpringValidationExecutor( ValidationExecutor pValidationExecutor ) {
    validationExecutor = pValidationExecutor;
  }
}
